### ISSUE TITLE
KeyError: 'data/data_generators/tmp/data/vigenere_brown_vocab_200'

### ISSUE THREAD

**Issue by c1a1o1** [for-ai/CipherGAN#2]
C:\Users\caocao\Anaconda3\python.exe D:/work/gan-pix2pix/CipherGAN-master/CipherGAN-master/train.py --output_dir=runs/vig345 \ --test_name=data/data_generators/tmp/data/vigenere345-brown200-eval* \ --train_name=data/data_generators/tmp/data/vigenere345-brown200-train* \ --hparam_sets=data/data_generators/tmp/data/vigenere_brown_vocab_200
Traceback (most recent call last):
  File "D:/work/gan-pix2pix/CipherGAN-master/CipherGAN-master/train.py", line 89, in <module>
    tf.app.run()
  File "C:\Users\caocao\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:/work/gan-pix2pix/CipherGAN-master/CipherGAN-master/train.py", line 85, in main
    _run_locally(FLAGS.train_steps, FLAGS.eval_steps)
  File "D:/work/gan-pix2pix/CipherGAN-master/CipherGAN-master/train.py", line 42, in _run_locally
    hparams = get_hparams(FLAGS.hparam_sets)
  File "D:\work\gan-pix2pix\CipherGAN-master\CipherGAN-master\hparams\registry.py", line 20, in get_hparams
    curr = _HPARAMS[name]
KeyError: 'data/data_generators/tmp/data/vigenere_brown_vocab_200'

**Comment by osama** [comment]
There are likely two issues here:
1. You likely don't have the expected generated data due to #1 
2. You don't need to pass a path in for `hparam_sets`. Instead, try `--hparam_sets=vigenere_brown_vocab_200`

**Comment by c1a1o1** [comment]
Thank s very much!
